sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
cache:
  yarn: true


before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

deploy:
  provider: firebase
  token:
    secure: "HgoYLkUHdOlr//knFyElmU85c8TMmYNpNBRFdMidSyc0kiquzwTuvdZ0dZIsaOmw7la2wOgHlg2MSSekAirUqlGTYTC6gk8R95wG8vkKhDNWvONiy7BlZ+TkTXPDHTgAicXjQmSluEpJoaz7GhV3flbuNfv/pXZfeI21cXmN3Wpz2vzolWHV99098eraVb+D95OfFnfrA+vAMgVl51pmzHCT2MALCph7mlJPqGJHCUfw6mxX0rT+KI9i37OwgIvrhbZRW0noLnxw+4tjdlJyyDV6JLpsLUmlCzlHVq4iSgXimfT1v0lo2qvgIgdIuYOrS5/A3hVrYJiOiHKQipQvOVyxgv1fndUMhCmHAUS48Puj1IHVJUdVOqJihqOEsI/yww7/ij15RninNe3ds56YuM9ZvpPQCVU72esrydDraTaMoFKpJvFrB+gA6cefvJ+N8n7TFVJr3C4WTYWdPm8rY9lOdYPTEDa4ojCDnEB5WGa3gWYIlQpKA1jLCcVXI44xZ2dzbODYBrnMgj8TlXG5hHzWntMDJXfdgZmmvb6SCHyhP4WKozy6Lxdwfsysa8sXqzjW7wOcF49SytViE8fkDKb7DGIpiZhibYNW/Ls3zc6X01CrZM1TlS1rLGdznieAL7myR9VM7jaHWxa3CXYNJ5cKPWcptpnCsxGao7lEBh4="
